# .bash_profile

# If not running interactively, don't do anything
[[ -z "$PS1" ]] && return

# Source local definitions (if any)
for script in ~/.profile.d/{git-*,function,function_*,path,env,grep,alias,prompt,*}.sh ; do
	source $script
done
unset -v script

# Get the aliases and functions
if [[ -f ~/.bashrc ]] ; then
        source ~/.bashrc
fi
