# .bashrc

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# source global definitions (if any)
if [[ -f /etc/bashrc ]] ; then
        source /etc/bashrc
fi

# Source local definitions (if any)
for script in ~/.bashrc.d/*.sh ; do
	source $script
done
unset -v script
